// Copyright 2022, the Flutter project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

const gameLevels = [
  GameLevel(
    number: 1,
    layers: 2,
    adjRule: [1, 2, 3],
    ringRule: [1, 1],
    par: 4,
  ),
  GameLevel(
    number: 2,
    layers: 2,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 3,
    layers: 2,
    adjRule: [0, 1],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 4,
    layers: 2,
    adjRule: [3, 6],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 5,
    layers: 3,
    adjRule: [0],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 6,
    layers: 3,
    adjRule: [2, 4],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 7,
    layers: 3,
    adjRule: [1, 2, 3],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 8,
    layers: 3,
    adjRule: [2, 3, 4],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 9,
    layers: 3,
    adjRule: [6, 2],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 10,
    layers: 3,
    adjRule: [4, 2],
    ringRule: [1, 2],
    par: 1,
  ),
  GameLevel(
    number: 11,
    layers: 4,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 12,
    layers: 4,
    adjRule: [1, 2],
    ringRule: [1, 2],
    par: 1,
  ),
  GameLevel(
    number: 13,
    layers: 4,
    adjRule: [1, 2, 3],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 14,
    layers: 4,
    adjRule: [1, 2, 3, 4, 5, 6],
    ringRule: [1, 3],
    par: 1,
  ),
  GameLevel(
    number: 15,
    layers: 4,
    adjRule: [2, 4, 6],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 16,
    layers: 4,
    adjRule: [0],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 17,
    layers: 4,
    adjRule: [0],
    ringRule: [1, 2],
    par: 1,
  ),
  GameLevel(
    number: 18,
    layers: 4,
    adjRule: [1, 2, 5],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 19,
    layers: 4,
    adjRule: [1, 2, 5],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 20,
    layers: 4,
    adjRule: [4, 2, 1],
    ringRule: [2, 3],
    par: 1,
  ),
  GameLevel(
    number: 21,
    layers: 4,
    adjRule: [3, 2],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 22,
    layers: 4,
    adjRule: [4, 2, 3],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 23,
    layers: 4,
    adjRule: [4, 2, 6],
    ringRule: [2, 3],
    par: 25,
  ),
  GameLevel(
    number: 24,
    layers: 4,
    adjRule: [1, 2, 3],
    ringRule: [2, 3],
    par: 25,
  ),
  GameLevel(
    number: 25,
    layers: 4,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 1,
  ),
  GameLevel(
    number: 26,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 27,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 28,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 29,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 30,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 31,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 32,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 33,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 34,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 35,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 36,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 37,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 38,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 39,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 40,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 41,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 42,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 43,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 44,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 45,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 46,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 47,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 48,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 49,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 50,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 51,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 52,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 53,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 54,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 55,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 56,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 57,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 58,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 59,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 60,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 61,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 62,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 63,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 64,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 65,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 66,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 67,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 68,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 69,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 70,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 71,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 72,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 73,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 74,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 75,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 76,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 77,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 78,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 79,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 80,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 81,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 82,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 83,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 84,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 85,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 86,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 87,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 88,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 89,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 90,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 91,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 92,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 93,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 94,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 95,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 96,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 97,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 98,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 99,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  ),
  GameLevel(
    number: 100,
    layers: 5,
    adjRule: [4, 2],
    ringRule: [1, 1],
    par: 25,
  )
];

class GameLevel {
  final int number;
  final int layers;

  final List<int> adjRule;
  final List<int> ringRule;
  final int par;

  /// The achievement to unlock when the level is finished, if any.
  final String? achievementIdIOS;

  final String? achievementIdAndroid;

  bool get awardsAchievement => achievementIdAndroid != null;

  const GameLevel({
    required this.number,
    required this.adjRule,
    required this.ringRule,
    required this.par,
    required this.layers,
    this.achievementIdIOS,
    this.achievementIdAndroid,
  }) : assert(
            (achievementIdAndroid != null && achievementIdIOS != null) ||
                (achievementIdAndroid == null && achievementIdIOS == null),
            'Either both iOS and Android achievement ID must be provided, '
            'or none');
}
